# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  go:
    inputs:
      ENVIRONMENT
      COLLECTIONS
      DBFILE_PATH
      REQUEST_LIMIT
      IMAGEFINDER_SLEEP_DURATION_SECONDS
      WORLDVIEW_API_KEY
    runs:
      using: 'docker'
      image: 'Dockerfile'

   
  
