# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
#     - name: set venv home directory
#       run: |
#         export PIPENV_VENV_IN_PROJECT="enabled"
#         pip install --upgrade pip
#         pip install --user pipenv
#         pipenv install

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Packages
      working-directory: client
      run: npm install
      
    - name: Build frontend
      working-directory: client
      run: CI=false npm run build
      
    - name: Build environment file
      run: |
        touch worldview.conf
        echo COLLECTIONS=641217,228275,370126,3129418 >> worldview.conf
        echo ENVIRONMENT=production >> worldview.conf
        echo DBFILE_PATH=/var/lib/worldview/index.db >> worldview.conf
        echo REQUEST_LIMIT=11 >> worldview.conf
        echo IMAGEFINDER_SLEEP_DURATION_SECONDS=900 >> worldview.conf
        echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> worldview.conf
        echo WORLDVIEW_API_KEY=${{ secrets.API_KEY }} >> worldview.conf

    - name: ls
      run: ls -a
    
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "worldview.conf"
        target: "/etc/worldview"

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "client/build/*"
        target: "/var/www/greenboy.io/worldview/html"
        strip_components: 2

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "wsgi.py, app, Pipfile, Pipfile.lock"
        target: "/srv/worldview"
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: | 
          cd /srv/worldview
          pipenv uninstall --all
          pipenv install      
          
    - name: Restart app
      run: systemctl start worldview.service
        
  
